function macros() {
#macro directions -1
#macro right 0
#macro up 1
#macro left 2
#macro down 3
#macro r 4
#macro g 5
#macro b 6
#macro cast 7
#macro abi 8
#macro jump 9
#macro look 10
#macro altfire 11
#macro channel 12
#macro inventory_1 13
#macro inventory_2 14
#macro inventory_3 15
#macro inventory_4 16
#macro colorinfo 17
#macro pause 18
#macro aim_x 19
#macro aim_y 20
#macro confirm 25
#macro cancel 26
#macro stepmode 27
#macro free 0
#macro pressed 1
#macro held 2
#macro released 3
#macro axis 4
#macro cpu_control -1
#macro keyboard 0
#macro mouse 1
#macro gui_input 2
#macro no_control -1
#macro cpu_control_set 0
#macro keyboard1 1
#macro keyboard2 2
#macro gamepad 3
#macro gamepad_right 1
#macro gamepad_up 2
#macro gamepad_left 3
#macro gamepad_down 4
#macro gamepad_stick 5
#macro g_nothing -1
#macro g_dark 0
#macro g_red 1
#macro g_green 2
#macro g_blue 4
#macro g_yellow 3
#macro g_magenta 5
#macro g_cyan 6
#macro g_white 7
#macro g_octarine 8
#macro shape_inherit -1
#macro shape_circle 0
#macro shape_rect 1
#macro hp_shield 0
#macro hp_weapon 1
#macro hp_body 2
#macro hp_movement 3
#macro core_none -1
#macro core_insulator 0
#macro core_energy 1
#macro core_item 2
#macro core_gate_pass 3
#macro cover_none -1
#macro cover_indestr 0
#macro cover_armor 1
#macro cover_grate 2
#macro spd_none 0
#macro spd_veryslow 1
#macro spd_slow 2
#macro spd_normal 3
#macro spd_fast 4
#macro spd_veryfast 5
#macro spd_instant 6
}
