function macros() {
#macro directions -1
#macro right 0
#macro up 1
#macro left 2
#macro down 3
#macro r 4
#macro g 5
#macro b 6
#macro cast 7
#macro abi 8
#macro jump 9
#macro look 10
#macro altfire 11
#macro channel 12
#macro inventory_1 13
#macro inventory_2 14
#macro inventory_3 15
#macro inventory_4 16
#macro aim_x 17
#macro aim_y 18
#macro confirm 20
#macro cancel 21
#macro stepmode 22
#macro free 0
#macro pressed 1
#macro held 2
#macro released 3
#macro axis 4
#macro cpu_control -1
#macro keyboard 0
#macro joystick 1
#macro mouse 2
#macro gui_input 3
#macro no_control -1
#macro cpu_control_set 0
#macro keyboard1 1
#macro keyboard2 2
#macro joypad1 3
#macro joypad2 4
#macro gamepad 5
#macro joy_rtrigger 20
#macro joy_ltrigger 21
#macro joy_right 22
#macro joy_up 23
#macro joy_left 24
#macro joy_down 25
#macro joy_dpad_right 26
#macro joy_dpad_up 27
#macro joy_dpad_left 28
#macro joy_dpad_down 29
#macro joy_none 30
#macro joy_any 31
#macro joy_look 32
#macro gamepad_right 1
#macro gamepad_up 2
#macro gamepad_left 3
#macro gamepad_down 4
#macro gamepad_stick 5
#macro g_nothing -1
#macro g_black 0
#macro g_red 1
#macro g_green 2
#macro g_blue 4
#macro g_yellow 3
#macro g_purple 5
#macro g_azure 6
#macro g_white 7
#macro g_octarine 8
#macro shape_inherit -1
#macro shape_circle 0
#macro shape_rect 1
#macro hp_shield 0
#macro hp_weapon 1
#macro hp_body 2
#macro hp_movement 3
#macro core_none -1
#macro core_insulator 0
#macro core_energy 1
#macro core_item 2
#macro core_gate_pass 3
#macro cover_none -1
#macro cover_indestr 0
#macro cover_armor 1
#macro cover_grate 2
#macro spd_none 0
#macro spd_veryslow 1
#macro spd_slow 2
#macro spd_normal 3
#macro spd_fast 4
#macro spd_veryfast 5
#macro spd_instant 6
#macro coltypes_max -10
#macro coltype_blocking -10



}
